# Generated by Django 5.2.10 on 2026-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(default=5.0),
        ),
    ]
