# Generated by Django 5.2.13 on 2026-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_type',
            field=models.CharField(choices=[('document', 'Документ'), ('package', 'Посылка')], default='document', max_length=20),
        ),
    ]
